%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.21.0 on {{2018,7,26},{10,52,19}}

-ifndef(my_client_v2_sample_func).
-define(my_client_v2_sample_func, true).

-define(my_client_v2_sample_func_gpb_version, "3.21.0").

-ifndef('MY_CLIENT_V2.SAMPLE.FUNC.FACT_PB_H').
-define('MY_CLIENT_V2.SAMPLE.FUNC.FACT_PB_H', true).
-record('my_client_v2.sample.func.Fact',
        {x                              % = 1, int32
        }).
-endif.

-ifndef('MY_CLIENT_V2.SAMPLE.TYPE.FACTRESP_PB_H').
-define('MY_CLIENT_V2.SAMPLE.TYPE.FACTRESP_PB_H', true).
-record('my_client_v2.sample.type.FactResp',
        {y                              % = 1, int32
        }).
-endif.

-endif.
